import { Trend } from '../types';

export function exportTrendToPDF(trend: Trend) {
  const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${trend.label}</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      line-height: 1.6;
      color: #333;
      max-width: 800px;
      margin: 0 auto;
      padding: 40px 20px;
    }
    h1 {
      color: #1a1a1a;
      font-size: 28px;
      margin-bottom: 20px;
      border-bottom: 3px solid #2563eb;
      padding-bottom: 10px;
    }
    .metadata {
      display: flex;
      gap: 10px;
      margin-bottom: 30px;
      flex-wrap: wrap;
    }
    .badge {
      padding: 6px 12px;
      border-radius: 6px;
      font-size: 12px;
      font-weight: 600;
    }
    .badge-high {
      background-color: #fee2e2;
      color: #991b1b;
    }
    .badge-medium {
      background-color: #fef3c7;
      color: #92400e;
    }
    .badge-low {
      background-color: #d1fae5;
      color: #065f46;
    }
    .badge-technology {
      background-color: #dbeafe;
      color: #1e40af;
    }
    .badge-society {
      background-color: #e9d5ff;
      color: #6b21a8;
    }
    .badge-economy {
      background-color: #d1fae5;
      color: #065f46;
    }
    .badge-environment {
      background-color: #d1fae5;
      color: #047857;
    }
    .badge-ring {
      background-color: #f3f4f6;
      color: #374151;
    }
    h2 {
      color: #1a1a1a;
      font-size: 18px;
      margin-top: 30px;
      margin-bottom: 15px;
      text-transform: uppercase;
      letter-spacing: 0.5px;
    }
    .summary {
      margin-bottom: 30px;
      font-size: 16px;
      line-height: 1.8;
    }
    .info-grid {
      display: grid;
      grid-template-columns: repeat(2, 1fr);
      gap: 15px;
      margin-top: 30px;
    }
    .info-item {
      background-color: #f9fafb;
      padding: 15px;
      border-radius: 6px;
      border-left: 4px solid #2563eb;
    }
    .info-label {
      font-size: 12px;
      font-weight: 600;
      color: #6b7280;
      text-transform: uppercase;
      letter-spacing: 0.5px;
      margin-bottom: 5px;
    }
    .info-value {
      font-size: 14px;
      color: #1a1a1a;
      font-weight: 500;
    }
    .footer {
      margin-top: 50px;
      padding-top: 20px;
      border-top: 1px solid #e5e7eb;
      font-size: 12px;
      color: #6b7280;
      text-align: center;
    }
  </style>
</head>
<body>
  <h1>${trend.label}</h1>

  <div class="metadata">
    <span class="badge badge-${trend.impact.toLowerCase()}">${trend.impact} Impact</span>
    <span class="badge badge-${trend.quadrant.toLowerCase()}">${trend.quadrant}</span>
    <span class="badge badge-ring">${trend.ring}</span>
  </div>

  <h2>Summary</h2>
  <div class="summary">
    ${trend.summary}
  </div>

  <h2>Details</h2>
  <div class="info-grid">
    <div class="info-item">
      <div class="info-label">Quadrant</div>
      <div class="info-value">${trend.quadrant}</div>
    </div>
    <div class="info-item">
      <div class="info-label">Timeline</div>
      <div class="info-value">${trend.ring}</div>
    </div>
    <div class="info-item">
      <div class="info-label">Impact Level</div>
      <div class="info-value">${trend.impact}</div>
    </div>
    <div class="info-item">
      <div class="info-label">Created</div>
      <div class="info-value">${new Date(trend.created_at).toLocaleDateString()}</div>
    </div>
  </div>

  <div class="footer">
    Generated by Trend Radar<br>
    ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
  </div>
</body>
</html>
  `;

  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${trend.label.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.html`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
